packages:
  - packages/*
  - docs

catalogs:
  build:
    astro: ^5.15.3
  deps:
    '@astrojs/mdx': ^4.3.9
    '@byronogis/postcss-global-data': ^1.0.1
    astro-color-scheme: ^1.1.5
    astro-integration-kit: ^0.19.1
    c12: ^3.3.1
    dayjs: ^1.11.18
    defu: ^6.1.4
    jiti: ^2.6.1
    p-limit: ^7.2.0
    postcss-preset-env: ^10.4.0
    type-fest: ^5.1.0
    typescript: ^5.9.3
    unocss: ^66.5.4
    unocss-preset-scrollbar: ^3.2.0
    zx: ^8.8.5
  docs:
    typedoc: ^0.28.14
    typedoc-plugin-frontmatter: ^1.3.0
    typedoc-plugin-markdown: ^4.9.0
  frontend:
    nprogress: ^0.2.0
    pixi.js: ^8.14.0
    simplex-noise: ^4.0.3
  icons:
    '@iconify-json/logos': ^1.2.10
    '@iconify-json/lucide': ^1.2.71
    '@iconify-json/uil': ^1.2.3
  lint:
    '@antfu/eslint-config': ^6.2.0
    '@unocss/eslint-plugin': ^66.5.4
    eslint: ^9.38.0
    eslint-plugin-astro: ^1.4.0
    husky: ^9.1.7
    lint-staged: ^16.2.6
    prettier-plugin-astro: ^0.14.1
    simple-git-hooks: ^2.13.1
  release:
    bumpp: ^10.3.1
    changelogen: ^0.6.2
  seo:
    '@astrojs/rss': ^4.0.13
    '@astrojs/sitemap': ^3.6.0
    '@vercel/og': ^0.8.5
    astro-seo: ^0.8.4
  shiki:
    '@shikijs/transformers': ^3.14.0
  types:
    '@types/nprogress': ^0.2.3
  unified:
    rehype-parse: ^9.0.1
    rehype-remark: ^10.0.1
    remark-gfm: ^4.0.1
    remark-stringify: ^11.0.0
    unist-util-visit: ^5.0.0

enablePrePostScripts: true

shamefullyHoist: true
